### ISSUE TITLE
Using BladeRF with Soapy instructions for BladeRF missing

### ISSUE THREAD

**Issue by Bottesch** [5G-MAG/rt-mbms-modem#19]
Step 2.1 of https://github.com/5G-MAG/rt-mbms-modem#readme

if using Blade RF as SDR:
after installing rt-mbms-modem using the instructions below you must modify a rt-mbms configuration parameter in /etc/5gmag-rt.conf from:

    device_args = "driver=lime";
    antenna = "LNAW";
to
device_args = "driver=bladerf";
    antenna = "RX";

**Comment by dsilhavy** [comment]
Thank you, added this to the documentation
