### ISSUE TITLE
VLC unable to connect to offered streams from mbms modem

### ISSUE THREAD

**Issue by Simons-CSharp** [5G-MAG/rt-mbms-modem#23]
I have the mbms modem running and it is offering 6 streams to me (see picture
![SixStreams](https://user-images.githubusercontent.com/50143924/150151821-6fedbbac-330d-4b27-b78e-b1cda83d01bf.png)
)

When I run VLC and use the Media>Open Network Stream> and enter rtp://232.1.1.112:40002 . I get the error cannot join multicast group. No such device.

Things I've tried:
In the 5gmag-rt file I have change the interface from eno1 to my devices (enp0s31f6)

It seems the modem is not tunnelling the streams.

Do you have any ideas?

Thank-you
Simon

**Comment by dsilhavy** [comment]
One more thing: Try to add an `@` to the address in VLC: `rtp://@239.11.4.10:5520`

**Comment by Simons-CSharp** [comment]
Hi,
IT would appear to be a CPU load issue. My set up is i7 Gen7. The gui is showing 99% load, so I think for 6 streams I'll need a more powerful CPU. I'll update this message when I try a more powerful PC.

**Comment by Simons-CSharp** [comment]
Update - changed for a Ryzen based system and streams all appeared. All that was needed was more CPU power for 6 streams!
Thanks.
