### ISSUE TITLE
5gmag-rt-modem.service can't find bladerf

### ISSUE THREAD

**Issue by FMPandolfi** [5G-MAG/rt-mbms-modem#27]
**Describe the bug**
On Ubuntu 20.04, when starting the modem as a daemon, it prompts an error saying `bladerf_open_with_devinfo() returned -7 - No device(s) available`. The modem service does not work properly and nothing is displayed in the wui. `fivegmag-rt` is already in the sudoers list and the command `sudo setcap 'cap_sys_nice=eip' usr/local/bin/modem` was prompted as well. If modem is run through the command line, though, everything works as intended.

**To Reproduce**
1. Run 'sudo systemctl start 5gmag-rt-modem.service'

**Expected behavior**
Modem can find bladerf SDR and start as intended.

**Screenshots**
![Screenshot from 2022-02-09 15-11-52](https://user-images.githubusercontent.com/85676390/153221225-179a603a-b08f-442b-b078-402fc389ecf3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 96.0

**Additional context**
Intel NUC10 i7, BladeRF.

**Comment by FMPandolfi** [comment]
![Screenshot from 2022-02-09 15-11-52](https://user-images.githubusercontent.com/85676390/153221954-3a2d76b2-7dfe-42f0-8442-5d8bd72bd414.png)

**Comment by dsilhavy** [comment]
@FMPandolfi Please check the troubleshooting guide here: https://github.com/5G-MAG/Documentation-and-Architecture/wiki/MBMS-Modem#troubleshooting-insufficient-permissions-when-trying-to-open-sdr 

Try adding your username and group and launch the process again

**Comment by dsilhavy** [comment]
Closing this for now, please comment if you still encounter the problem
