### ISSUE TITLE
The 5gmag modem receives normally, but cannot receive IP packets from Ethernet

### ISSUE THREAD

**Issue by Flash0406** [5G-MAG/rt-mbms-modem#33]
Hi 5G-MAG expert group，

We use our own 5g broadcast transmitter to connect with 5gmag receiver . The 5gmag receiver works normally, but the IP packet cannot be obtained from Ethernet.

However, when we use sample file to receive, we can obtain IP packets in the same environment.

By comparing the log files generated by the two modes, it is found that the process has reached GW write_ pdu_ MCH function. There are both printing messages such as "RX MCH PDU...." and there is no error message about "DL TUN / TAP".

Attach file is contain syslog for two test mode. FIle “syslog_20220401_right“ is reported when using sample file and “syslog_20220401_wrong“ is reported when using SDR.
[debug_log.zip](https://github.com/5G-MAG/rt-mbms-modem/files/8398347/debug_log.zip)

Please help to see where is the problem, thanks!

**Comment by Flash0406** [comment]
when VLC is used to generate RTP video IP streams on PC TX, the TTL (Time to Live) in these IP packets is set to 0x1.
When the 5G-MAG receiver parsed the IP packet from the MCH and sent it to the Ubuntu Ethernet module, the Ethernet module found TTL=0x1 and discarded the IP packet.

**Comment by dsilhavy** [comment]
Thank you for pointing this out @Flash0406 . As an addition the basic architecture:
<img width="574" alt="Bildschirmfoto 2022-04-08 um 16 41 04" src="https://user-images.githubusercontent.com/2427039/162460452-3276ece0-e8b1-4b27-86e2-307a64f949f1.png">
