### ISSUE TITLE
Cell search and selection/bootstrap

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-mbms-modem#7]
Currently the bandwidth of the live signal or the prerecorded file needs to be manually defined. As part of this feature the automatic cell search and selection of the frequency range should be implented

**Comment by kuehnhammer** [comment]
As it is now, you do need to pass the bandwidth of a sample file, so the sample rate it was recorded at can be deduced.

For live signals, the modem can switch the sample rate of the SDR, and does go through a cell search process during which the required bandwidth ist autodiscovered.

**Comment by dsilhavy** [comment]
Not possible to do this for VoD, closing.
